project:
  type: website
  output-dir: _book

website:
  title: "Physics Notes"
  page-navigation: true
  sidebar:
    contents:
      - index.qmd

      - section: "Classical Mechanics"
        contents:
          - classical-mechanics/index.qmd

      - section: "Electrodynamics"
        contents:
          - electrodynamics/index.qmd

      - section: "Quantum Mechanics"
        contents:
          - quantum-mechanics/index.qmd

      - section: "Statistical Physics"
        contents:
          - statistical-physics/index.qmd

      - section: "Quantum Field Theory"
        contents:
          - quantum-field-theory/index.qmd

      - section: "Hadron Collider Physics"
        contents:
          - hadron-colliders/index.qmd
          - hadron-colliders/index.qmd
          - hadron-colliders/kinematics.qmd
          - hadron-colliders/factorisation.qmd
          - hadron-colliders/parton-showers.qmd
          - hadron-colliders/monte-carlo-generators.qmd
          - section: "Higgs Physics"
            contents:
              - hadron-colliders/higgs-physics/index.qmd
              - hadron-colliders/higgs-physics/production-modes.qmd
              - hadron-colliders/higgs-physics/higgs-transverse-momentum.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    html-math-method: katex

execute:
  freeze: auto
