project:
  type: book

book:
  title: "Physics Notes"
  author: "Jan Lukas Späh"
  page-navigation: true

  chapters:
    - index.qmd

    - part: "Classical Mechanics"
      chapters:
        - classical-mechanics/index.qmd

    - part: "Electrodynamics"
      chapters:
        - electrodynamics/index.qmd

    - part: "Quantum Mechanics"
      chapters:
        - quantum-mechanics/index.qmd

    - part: "Statistical Physics"
      chapters:
        - statistical-physics/index.qmd

    - part: "Quantum Field Theory"
      chapters:
        - quantum-field-theory/index.qmd

    - part: "Collider Physics"
      chapters:
        - collider-physics/index.qmd
        - collider-physics/hadron-colliders/index.qmd
        - collider-physics/hadron-colliders/kinematics.qmd
        - collider-physics/hadron-colliders/factorisation.qmd
        - collider-physics/hadron-colliders/parton-showers.qmd
        - collider-physics/hadron-colliders/monte-carlo-generators.qmd
        - collider-physics/hadron-colliders/higgs-physics/index.qmd
        - collider-physics/hadron-colliders/higgs-physics/production-modes.qmd
        - collider-physics/hadron-colliders/higgs-physics/higgs-transverse-momentum.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    html-math-method: katex

execute:
  freeze: auto